volumes:
  postgres_data:

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - PGUSER=assignment_2_user
      - POSTGRES_USER=assignment_2_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=assignment_2_db
    ports:
      - "5432:5432"
